openapi: 3.0.3
info:
  title: User and Student Enrollment API
  version: 1.0.0
  description: API for managing user and student enrollment information

tags:
  - name: Users
    description: Endpoints related to user management
  - name: Enrollment
    description: Endpoints related to student enrollment

paths:
  /users:
    post:
      summary: Create a new user (can be a student or a teacher)
      tags:
        - Users
      parameters:
        - name: userType
          in: query
          description: Specify the type of user (student or teacher)
          required: true
          schema:
            type: string
            enum: 
              - student
              - teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/UserRequest'
                
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                message: User created successfully
        '400':
          description: Invalid input
          content:
            application/json:
              example:
                message: Invalid input

  /enrollments:
    post:
      summary: Create a new enrollment
      tags:
        - Enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentRequest'
      responses:
        '201':
          description: Enrollment created successfully
          content:
            application/json:
              example:
                message: Enrollment created successfully
        '400':
          description: Invalid input
          content:
            application/json:
              example:
                message: Invalid input

  '/enrollments/{enrollment_id}':
    put:
      summary: Update an enrollment by Enrollment ID
      tags:
        - Enrollment
      parameters:
        - name: enrollment_id
          in: path
          required: true
          description: ID of the enrollment to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentUpdateRequest'
      responses:
        '200':
          description: Enrollment updated successfully
          content:
            application/json:
              example:
                message: Enrollment updated successfully
        '400':
          description: Invalid input data
          content:
            application/json:
              example:
                message: Invalid input data
        '404':
          description: Enrollment not found
          content:
            application/json:
              example:
                message: Enrollment not found
        '405':
          description: Validation exception
          content:
            application/json:
              example:
                message: Validation exception

components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "johndoe@example.com"
        password:
          type: string
          example: "********"


    EnrollmentRequest:
      type: object
      properties:
        student_id:
          type: string
          example: "20238"
        course_name:
          type: string
          example: "Mathematics 101"

    EnrollmentUpdateRequest:
      type: object
      properties:
        status:
          type: string
          example: "Accepted"
